### ISSUE TITLE
pre-recorded scenario JSON file

### ISSUE THREAD

**Issue by fix-six** [ajhsu/chromecast-device-emulator#5]
As you writed  "What emulator did, is try to REPLAY the IPC messages between sender and receiver. Which means that you have to PRE-RECORD from a real Google Cast device to get these IPC message", if there is not Google Cast Device then can't to test receiver. That's a pity.

**Comment by ajhsu** [comment]
@fix-six Indeed, the emulator so far is trying to reduce the number of redundant efforts during the receiver app development by automated replaying the IPC messages for you.

Would you like to share an example of your requirement so that we may evaluate if there's a possibility for further implementation?

**Comment by ajhsu** [comment]
@fix-six I'm going to close the in-active issue. Any further suggestions are still welcomed.
